### ISSUE TITLE
include feature to only consider certain tags

### ISSUE THREAD

**Issue by Emilgardis** [snok/container-retention-policy#10]
I want a feature to consider the removal only for certain tags which match a string (with regex/wildcard)

I imagine it would be something like this:

```
- uses: snok/container-retention-policy@v1
  with:
    image-names: dev, web, test
    cut-off: two hours ago UTC+2
    timestamp-to-use: updated_at
    account-type: org
    org-name: google
    keep-at-least: 1
    token: ${{ secrets.PAT }}
    consider-tags: sha-*
```

this would allow the user to only delete old images which match this/these filters, and not anything else. 

bikeshed on the name `consider-tags`, maybe `include-tags`, `filter-tags`?

This would also have to then include a feature to specify if untagged images should be considered as well.

Slightly related to #9
