### ISSUE TITLE
Add option to exclude recently pulled images

### ISSUE THREAD

**Issue by ddelange** [snok/container-retention-policy#101]
Hi 👋 

It would be awesome if we could protect recently pulled images from deletion.

The following stats are available in GitHub UI:
<img width="175" alt="Image" src="https://github.com/user-attachments/assets/831de3d0-f4ac-400f-a58d-7185003e1dcc" />

We have the following job running to clean up our org:
```yaml
jobs:
  container_retention_policy:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GH_BOT_TOKEN }}
          image-names: '*'
          keep-n-most-recent: 20
          cut-off: 4w
```

The above combination of `keep-n-most-recent` and `cut-off` is *pretty* safe, but leaves the chance of deleting production images in case there were no pushes to `main` for a repo for more than 4 weeks, plus we accumulated more than 20 dev commits pushed from PRs / feature branches.

I would love to replace these two options with a single "not been pulled for 30 days" filter. That would also leave a slight chance in case our kubernetes cluster didn't rebalance for 30 days and had to re-pull to a new node, but that chance is very small (much smaller than the chance of the above scenario for some of our less actively developed repos).
