### ISSUE TITLE
[bug] wrong behaviour when inputs: 'filter-tags' + 'filter-include-untagged' are empty instead of None

### ISSUE THREAD

**Issue by thpham** [snok/container-retention-policy#15]
When using the following action declaration:

```yaml
- name: Delete 'testing' image tags older than 2 weeks
  uses: snok/container-retention-policy@v1
  with:
    image-names: ${{ github.event.repository.name }}
    cut-off: 2 weeks ago UTC
    timestamp-to-use: created_at
    account-type: org
    org-name: ${{ github.repository_owner }}
    token: ${{ secrets.TOKEN }}
    keep-at-least: 0
    skip-tags: latest, main-*
```

The arguments `filter-tags` and `filter-include-untagged` are passed as empty strings within the running action container. This makes the behaviour different than when testing in command line.
you can check the following screenshot:
![container-retention-policy-bugs](https://user-images.githubusercontent.com/224674/149231449-f79a0e51-5732-4f73-b29c-f8022140e234.png)

A fix would be very much appreciated ! thank you very much for you work !
