### ISSUE TITLE
Ignore public images with more than 5000 downloads

### ISSUE THREAD

**Issue by Siemienik** [snok/container-retention-policy#20]
Hi, thank you for your effort to create this action :)
I'm writing to ask you, about the possibility to ignore tags which has more than 5000 downloads? Currently, each run tries to remove the same tags which are unavailable to remove.

Thanks in advance,

**Comment by sondrelg** [comment]
Are you saying Github's container registry won't let you delete an image with more than 5000 downloads? I wasn't aware that was a feature; can you link the docs? 🙂

**Comment by sondrelg** [comment]
Found the mention in the docs. Do you know if there's a way to retrieve the download count? I can't see one.

docs: https://docs.github.com/en/rest/reference/packages

**Comment by sondrelg** [comment]
Another option might be to just handle the specific error, but I don't have a public image with 5000 downloads to test on. Would you be interested in creating a PR for this @Siemienik?

**Comment by Siemienik** [comment]
Here are some ci runs which shows the situation that I mention: https://github.com/handsontable/handsontable/actions/workflows/ghcr-cleanup.yml?query=branch%3Afeature%2Fissue-9123

> Would you be interested in creating a PR for this @Siemienik?

Yeah, I would however I can't promise that I will have any free time, even more, that I've just finished working for HOT and It will be soon out of my dutes.

**Comment by sondrelg** [comment]
I looked over the different APIs available to us now @Siemienik and can't find and endpoint that lists download counts, so I don't think there's a simple way to avoid the `request.delete` calls. 

We can change the communication here though. What do you think about #21? Would you be able to test  running the action with `uses: snok/container-retention-policy@1c634b2fbfbadeda00368373761cccf6496f628a` to see if it works as expected?

**Comment by Siemienik** [comment]
Yeah, I'm going to test that on Monday, I reviewed the PR, and looks promising:+1:

**Comment by Siemienik** [comment]
Hi @sondrelg, I run a test: https://github.com/handsontable/handsontable/runs/5006183957?check_suite_focus=true#step:3:16

Information about the tag will be quite useful there

**Comment by sondrelg** [comment]
Hehe, I agree 👍  Thanks for testing, I'll update the PR and release later today

**Comment by sondrelg** [comment]
So I think with the outputs that will be added to the action when I release a new version right after posting this, all the info you need to skip images for the next run is actually available.

This is how you could do it:

```yaml
jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Cache image versions to skip
        uses: actions/cache@v2
        id: cache
        with:
          path: skip-image-versions.txt
          # key will always *not* match for a new commit, but
          # restore-key will match if there's a previously stored
          # file; so cache will *both be loaded and stored*.
          key: image-versions-to-skip-${{ github.sha }}
          restore-keys: image-versions-to-skip

      - name: Create file if it doesn't exist
        run: touch skip-image-versions.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Set image-versions output
        id: image-version
        # We cannot use `cat` directly in the input, but we can use an output from a step like this
        run: |
          images="$(cat skip-image-versions.txt)"
          echo $images
          echo "::set-output name=image-versions::$images"

      - name: Delete images more than 2 seconds old
        uses: snok/container-retention-policy@v1
        id: delete-images
        with:
          image-names: ghcr-retention-policy-test
          cut-off: 2 seconds ago UTC+2
          account-type: personal
          token: ${{ secrets.PAT }}
          skip-tags: ${{ steps.image-version.outputs.image-versions }}

      - name: Write skipped tags to cache
        run: |
          echo "${{ steps.delete-images.outputs.failed }}" > skip-image-versions.txt
```

The only thing that is missing here is that the output format and the format we're using when writing to `skip-tags` are not the same. To make this work 100%, you would need to change the outputs, that are, e.g.,

```
ghcr-retention-policy-test:123455,ghcr-retention-policy-test:123456
```

to just

```
123455,123456
```

The best place to perform that operation is probably in the "Set image-versions output" step, and that could probably be done with some bash shell script magic. In other words, I don't think another setting to read a file like this is strictly necessary.
