### ISSUE TITLE
Do you really need a personal access token?

### ISSUE THREAD

**Issue by sihil** [snok/container-retention-policy#27]
This looks really useful although I'm very reluctant to create a PAT.

Have you experimented to see whether this can be replaced with a `packages: write` permission? i.e.
```yaml
name: Delete old container images

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

permissions:
  packages: write

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete 'dev' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: python-dev, js-dev
          cut-off: A week ago UTC
          account-type: org
          org-name: my-org
          keep-at-least: 1
          untagged-only: true
```

This certainly lets you push and pull containers but I don't know if delete is included in `write`. I wondered if you knew one way or the other.
