### ISSUE TITLE
Need help getting this Action to work

### ISSUE THREAD

**Issue by ohueter** [snok/container-retention-policy#32]
I cannot get this Action to delete any images in my organization, and really cannot figure out the reason why ... I'd really appreciate any help :-)

It's a private repository, so let's assume the image name is `webapp-ui` (which is similar to the original) in an organization named `My-ORGA-Name` (both names include hyphens, if it matters).

My workflow file:
```yml
name: GitHub Container Registry

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  clean-ghcr:
    name: Delete unused container images
    runs-on: ubuntu-20.04

    steps:
      - name: Delete 'webapp-ui' containers older than a week
        uses: snok/container-retention-policy@v1
        with:
          image-names: webapp-ui
          cut-off: 1 week ago UTC
          timestamp-to-use: created_at
          account-type: org
          org-name: My-ORGA-Name
          token: ${{ secrets.GHCR_CLEANUP_ACCESS_TOKEN }}
```

The workflow runs without errors (on schedule and on dispatch) with the following output:
```
Run snok/container-retention-policy@v1
/usr/bin/docker run --name b314a111e5144cc41f6a4044fa17979c105_73b6dd --label 294b31 --workdir /github/workspace --rm -e INPUT_IMAGE-NAMES -e INPUT_CUT-OFF -e INPUT_TIMESTAMP-TO-USE -e INPUT_ACCOUNT-TYPE -e INPUT_ORG-NAME -e INPUT_TOKEN -e INPUT_UNTAGGED-ONLY -e INPUT_FILTER-INCLUDE-UNTAGGED -e INPUT_SKIP-TAGS -e INPUT_KEEP-AT-LEAST -e INPUT_FILTER-TAGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/webapp-ui/webapp-ui":"/github/workspace" 294b31:4a111e5144cc41f6a4044fa17979c105  "org" "My-ORGA-Name" "webapp-ui" "created_at" "1 week ago UTC" "***" "false" "" "0" "" "true"
No more versions to delete for webapp-ui
```

However, there are plenty of old images:
<img width="508" alt="ghcr" src="https://user-images.githubusercontent.com/57348167/166710375-18678787-62ab-4cc1-9baf-ec474f65de09.png">
(taken on URL: https://github.com/My-ORGA-Name/webapp-ui/pkgs/container/webapp-ui/versions)

The PAT has `delete:packages, read:packages` permissions. I've played with all parameters, but no images are deleted no matter what ...
