### ISSUE TITLE
With version 1.5.0 images are no longer deleted

### ISSUE THREAD

**Issue by eickehnn** [snok/container-retention-policy#41]
The following still worked up to version 1.4.2, with version 1.5.0 images are no longer deleted:
```yaml
  delete-older-images:
    name: Delete older ghcr images
    runs-on: ubuntu-latest
    steps:
      - name: Delete images
        uses: snok/container-retention-policy@v1
        with:
          image-names: repo/imagename
          cut-off: now UTC+1
          account-type: org
          org-name: my-org
          keep-at-least: 2
          skip-tags: latest
          token: ${{ secrets.PAT }}
```
Note: There is no log output or error message
