### ISSUE TITLE
Apply keep-at-least on the filtered tags list

### ISSUE THREAD

**Issue by artazar** [snok/container-retention-policy#47]
Hi, thanks for the great github action!

One thing I found worth getting improved: when image tags are filtered by 'filter-tags' parameter, the 'keep-at-least' value is still getting applied on the total list, rather than the filtered one.

The use case I would like to have covered is, as an example:
- Keep 5 most recent versions of "released" images by one filter (e.g. semver *.*.*)
- Keep 2 most recent versions of dev images for the rest of items by another filter.

So for the same repository I would like to run the action with 2 different filters and 2 different 'keep-at-least' values.

I can raise a PR to do that, as I've implemented and tested it, but could you please share your opinion on this suggestion?

I think in the current implementation, the behavior may be confusing for those who use any filters. In fact, this does not only refer to 'filter-tags', but all other conditions should be followed before applying 'keep-at-least' limitation.

**Comment by sondrelg** [comment]
That sounds useful :+1: Do you have an example of how the workflow definition would look for your example? 

I'm happy to review a PR for this :+1:

**Comment by sondrelg** [comment]
Thanks for the PR! 

With the regex match, how would the example look like instead? I'm having a hard time understanding the practical difference it would make.

**Comment by artazar** [comment]
With the regex I can just do it in a more precise manner like below, which I cannot do with the basic wildcard, as I just can't identify full numbers as separate patterns.

```
    steps:
      - name: Delete released images older than 1 week, keeping 5 most recent
        uses: snok/container-retention-policy@v1
        with:
          image-names: dev/*
          cut-off: One week ago UTC
          keep-at-least: 5
          filter-tags: '^([0-9]*\.)*[0-9]+-.*$'
          account-type: personal
          token: ${{ secrets.PAT }}
      - name: Delete pre-release images older than 1 day, keeping 1 most recent
        uses: snok/container-retention-policy@v1
        with:
          image-names: dev/*
          cut-off: One day ago UTC
          keep-at-least: 1
          filter-tags: '^([0-9]*\.)*[0-9]+$'
          account-type: personal
          token: ${{ secrets.PAT }}
```
