### ISSUE TITLE
Removing untagged images can damage tagged images

### ISSUE THREAD

**Issue by lukasz-mitka** [snok/container-retention-policy#63]
Running action like so
```yaml
      - name: Delete old untagged containers
        id: untagged
        uses: snok/container-retention-policy@96e897805acf21aa2ebc21fdf8e04c879e7daf9d # v2.0.1
        with:
          image-names: image
          account-type: org
          org-name: ${{ github.repository_owner }}
          cut-off: 2 weeks ago UTC
          untagged-only: true
          token: ***
```

Can damage tagged images:
```
$ docker pull ghcr.io/org/image:tag
tag: Pulling from org/image
manifest unknown
```

GitHub Support response:
> The way Docker publishes images changed recently. Instead of publishing images directly, it now publishes a hidden image alongside a manifest. You can see this below where it says OS / Arch (2). The (2) represents the hidden image and manifest.
This has the unfortunate consequence of breaking tools that detect untagged images (because the hidden image isn't tagged directly). When the hidden image is deleted, it leads to this manifest unknown error. Unfortunately there isn't an obvious fix for this.

`provenance` is enabled by default since `docker/build-push-action@v4`
My workaround is to disable it:
```yaml
 - uses: docker/build-push-action@v4
   with:
     provenance: false
     ...
```

Solution for already broken images: republish them

**Comment by sondrelg** [comment]
Do you propose we update the README of this action to notify users about this behaviour, or do you think this is something we can fix by changing the implementation?

**Comment by lukasz-mitka** [comment]
> Do you propose we update the README of this action to notify users about this behaviour, or do you think this is something we can fix by changing the implementation?

My understanding is there's no fix currently, but that's based on GH support answers, didn't verify it myself.

So I propose adding a warning in readme and pinning this issue for the time being.

**Comment by lukasz-mitka** [comment]
I have confirmed that disabling provenance (`provenance: false`) fixes the issue. Updated issue description.

Workaround:
```yaml
 - uses: docker/build-push-action@v4
   with:
     provenance: false
     ...
```
