### ISSUE TITLE
Unexpected behavior when filter-tags and dry-run are set

### ISSUE THREAD

**Issue by chris-schra** [snok/container-retention-policy#64]
First of all: thanks for the useful action.
I'm currently integrating it in our chore repo and as we have different deployment environments (reflected in the image tags), my idea is, to filter-tags by environment name (from a matrix), like this:

```yaml    
    strategy:
      matrix:
        # use a matrix to keep 3 images per environment
        environment: ['develop', 'feature', 'prod']
    steps:
      - name: Delete all containers (per environment) older than a month
        uses: snok/container-retention-policy@v2
        with:
          image-names: 'my-cool-image'
          cut-off: One month ago UTC
          account-type: org
          org-name: my-cool-org
          dry-run: true
          filter-tags: '${{ matrix.environment }}-*'
          filter-include-untagged: false
          keep-at-least: 3
          token: ${{ secrets.PAT }}
```

It seems, the execution (in terms of filter-tags string building) works as expected:
![retention](https://github.com/snok/container-retention-policy/assets/26594889/dd235be5-a341-44b8-bc61-378d67741377)

I expected that the dry-run will only return a few results, but it seems filter-tags is not working and dry-run states it would delete all tags older than a month (can't tell if keep-at-least is honored). Is there something wrong with my logic or with the filter-tags arg?
