### ISSUE TITLE
Support GH app generated tokens (deleting package versions for a user)

### ISSUE THREAD

**Issue by andreykaipov** [snok/container-retention-policy#72]
Currently there's three ways to delete packages:

1. [deleting a package version for an org](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#delete-package-version-for-an-organization)
2. [deleting a package version for the authenticated user](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#delete-a-package-version-for-the-authenticated-user)
3. [deleting a package version for a user](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#delete-package-version-for-a-user)

This action supports the first two via a PAT or the included `secrets.GITHUB_TOKEN` to auth on behalf of you.

I currently use GitHub app generated tokens in my workflows so I can avoid using PATs, but I'd also like the flexibility a PAT grants you like using multiple image names that aren't the same as the repo name. A brief overview of using GitHub app generated tokens in workflows can be found in the docs of another action: 
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens

In this case, the example for this action would look like:

```yaml
    steps:
      - uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          image-names: blah/*
          cut-off: one month ago EST
```

Using app generated tokens can be a third alternative for those reluctant to use PATs (https://github.com/snok/container-retention-policy/issues/27). However, if we try to use a GH app generated token currently, it will try to delete images owned by itself (which there are none), but what I expected to happen was it to delete images under my username.

I suppose if this were to be added, it could be specified as a third option to `token-type`, i.e. `pat`, `github-token`, `app-token`? And then maybe a new key like `owner` to specify the user, defaulting to `${{ github.repository_owner }}` if it's missing?

So something like:

account-type | token-type | owner/org-name | api endpoint
-|-|-|-
personal | github-token | n/a | delete authenticated user's images
personal | pat | n/a | delete authenticated user's images
personal | app-token | blah | delete user blah's images
org | github-token | blah | delete org blah's images
org | pat | blah| delete org blah's images
org | app-token | blah |  delete org blah's images

**Comment by sondrelg** [comment]
Yeah, though I haven't used a Github app like this myself, it seems like it should be fairly simple to implement. The most important thing will be to document it well, but you've done most of the job here already 🙂 I would accept a PR for this 👍

**Comment by sondrelg** [comment]
Hi again @andreykaipov,

I'm considering breaking the token input in a v3 release to support this. According to [this article](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/), PATs are identifiable by the `ghp` prefix, while a Github app would use tokens prefixed by `gho`, if I'm understanding things correctly.

I'm considering removing the `token-type` (which today can be 'pat' or 'github-token') and just having the `token` input, where a user can supply the value 'github-token' for us to use `$GITHUB_TOKEN`, or a valid PAT/Oauth token, which can be somewhat validated/inferred from the token prefix.

Does that sound reasonable to you?

**Comment by andreykaipov** [comment]
Hello! I think that's a great idea. Less options to choose from would simplify the configuration for the user.

It'd also be nice to combine the existing `org-name` option with the proposed `owner` option, because we can infer the `account-type` from that as well, e.g. hitting the following would show `type: "Organization"`:

https://api.github.com/users/snok
https://api.github.com/repos/snok/container-retention-policy

**Comment by sondrelg** [comment]
Agree! We can 

- consolidate `account-type` and `org-name` into an `owner` option
- remove `token-type` as described above
- remove `skip-tags` by implementing support for negative glob patterns in the `filter-tags` input (e.g., `filter-tags: l*, !latest`)
- replace `filter-include-untagged` and `untagged-only` with a new option: `tag-selection`, where the value can be "both", "tagged", or "untagged"

and I'm also tempted to rename `filter-tags` to `image-tags`, so that it would be closer to the `image-name` input parameter in name.

So instead of:

```
- uses: snok/container-retention-policy@v2
  with:
    image-names: dev, web, test*
    filter-tags: *
    skip-tags: latest
    account-type: org
    org-name: google
    token: ${{ secrets.PAT }}
    token-type: pat
    filter-include-untagged: true
    untagged-only: false
```

You would have something like:
```
- uses: snok/container-retention-policy@v2
  with:
    image-names: dev, web, test*
    image-tags: !*latest
    account: google
    token: ${{ secrets.PAT }}
    tag-selection: both
```

**Comment by sondrelg** [comment]
Hi @andreykaipov! Just wanted to say that I've added and tested GH app tokens in the v3-develop branch, which I hope to release soon. Hopefully in less than a week. 

Like you suggested, I've tested it, and plan to document that it should be set up like this:

```yaml
- name: Generate a token
  id: generate-token
  uses: actions/create-github-app-token@v1
  with:
    app-id: ${{ secrets.GH_APP_ID }}
    private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

- uses: snok/container-retention-policy@v3-develop
  name: Delete test-2-* images with an Github app token
  with:
    account: snok
    token: ${{ steps.generate-token.outputs.token }}
    cut-off: 2h
    image-names: container-retention-policy
```

In regards to your post:

> However, if we try to use a GH app generated token currently, it will try to delete images owned by itself (which there are none), but what I expected to happen was it to delete images under my username.

Can you elaborate a bit on this? I created an app and in the app settings, went to `Install app` and installed it for the `snok` organization. When running it, it deleted packages for the org. without any issue. Do you think it might work for you if you install it to your org/user account?

Here's the latest workflow run: https://github.com/snok/container-retention-policy/actions/runs/9341298060
