### ISSUE TITLE
Create new release without Node.js 16 dependencies

### ISSUE THREAD

**Issue by pfs-olwe99** [snok/container-retention-policy#79]
The current release (v2.2.1) is still using the setup-python@v4 action which gives a deprecation warning about Node.js 16. Can we get a new release now that main has been updated to use setup-python@v5?

**Comment by sondrelg** [comment]
Yes, sounds reasonable ☺️ Might take a little while, but it's on the list 👍

**Comment by ubbeK** [comment]
When will we get the next release? This issue was fixed in https://github.com/snok/container-retention-policy/pull/75.

This is a great GH action, better suited for my needs compared to https://github.com/actions/delete-package-versions, but I am a bit reluctant to implement it before a new release. And I rather not reference `main` branch until it is out.

**Comment by sondrelg** [comment]
I'm planning on releasing a new major version shortly, but could try to get this release out first @ubbeK 👍 Sorry about the delay

**Comment by ubbeK** [comment]
> I'm planning on releasing a new major version shortly, but could try to get this release out first @ubbeK 👍 Sorry about the delay

No worries. Who am I to complain about an open source project, keep up the good work! I will follow the releases of this repo.

**Comment by sondrelg** [comment]
I have been working on the v3 release for a while now, and it's getting close to being ready. I'm expecting to release the branch within a week or two, after writing some more documentation and tests, but consider the branch ready for testing. If anyone here would be interested in testing it, that would be very useful (and should resolve this issue for you) 🙇 

WIP documentation on how to migrate is contained in [migration.md](https://github.com/snok/container-retention-policy/blob/v3-develop/migration.md), and the new [readme](https://github.com/snok/container-retention-policy/tree/v3-develop) should contain any other info you should need.

The workflow should now be specified like this:

```yaml
- uses: snok/container-retention-policy@v3-develop
  with:
    account: snok  # org-name for an organization and the string "user" if you're deleting personal packages
    token: ${{ secrets.PAT }}
    image-names: container-retention-policy
    image-tags: test* dev* !dev-important # target any image that has a tag starting with the word test or dev, but not the image named "dev-important"
    tag-selection: both  # delete both tagged and untagged (replaced) images
    cut-off: 2w 3d
    dry-run: true
```

If you do test it, it would be great to get some feedback here!

**Comment by ubbeK** [comment]
> If you do test it, it would be great to get some feedback here!

I did try this out now

```yaml
on:
  workflow_call:
    inputs:
      cut_off:
        required: false
        type: string
        default: 3months
      keep_at_least:
        required: false
        type: number
        default: 10
      dry_run:
        required: false
        type: boolean
        default: false

jobs:
  ghcr_retention:
    runs-on: ubuntu-latest
    steps:
    - name: Set local variables
      run: |
        repo_name=${{ github.event.repository.name }}
        echo "repo_name_lowercase=${repo_name,,}" >> $GITHUB_ENV

    - name: Delete old ghcr images
      uses: snok/container-retention-policy@v3-develop
      with:
        image-names: ${{ env.repo_name_lowercase }}
        image-tags: "!latest"
        cut-off: ${{ inputs.cut_off }}
        timestamp-to-use: updated_at
        token: ${{ secrets.GITHUB_TOKEN }}
        account: ${{ github.repository_owner }}
        keep-at-least: ${{ inputs.keep_at_least }}
        dry-run: ${{ inputs.dry_run }}
```

where the following values for `inputs.cut_off` works
* `30d`
* `1month`
* `1months`
* `1month 8h`

However the following does not work, but it should according to the link that you are referencing here: https://github.com/snok/container-retention-policy/blob/v3-develop/migration.md -> https://crates.io/crates/duration-str

```
error: invalid value '1mon' for '--cut-off <CUT_OFF>': unknown time unit "mon", supported units: ns, us, ms, sec, min, hours, days, weeks, months, years (and few variations)
error: invalid value '1mon 8h' for '--cut-off <CUT_OFF>': unknown time unit "mon", supported units: ns, us, ms, sec, min, hours, days, weeks, months, years (and few variations)
```
