### ISSUE TITLE
v3 release

### ISSUE THREAD

**Issue by sondrelg** [snok/container-retention-policy#84]
If you notice any problems in the new release, please post them here 👍

**Comment by ubbeK** [comment]
Will there be a `v3` tag?

**Comment by ubbeK** [comment]
> Will there be a `v3` tag?

Sorry, didn't read the release notes to carefully

> We'll no longer maintain mutable major and minor version tags for the action. There will be no v3 target for the action, just v3.0.0 and other exact versions.

**Comment by sondrelg** [comment]
> > Will there be a `v3` tag?
> 
> Sorry, didn't read the release notes too carefully
> 
> > We'll no longer maintain mutable major and minor version tags for the action. There will be no v3 target for the action, just v3.0.0 and other exact versions.

No worries ☺️ I could be convinced otherwise, but what we've done in the past is just tag every patch release with the equivalent of `v3`, which in practice means everyone's on latest, and means you break everyone if you introduce an issue, which is inevitable. 

Dropping the mutable tags seems like it should:

- Give us more time to catch and fix new issues, before they reach too many people
- Makes it less likely that users will experience an issue, since it'll likely be fixed before most people upgrade

If you're worried about falling behind on action versions, I can recommend using dependabot for github actions, like we do [here](https://github.com/snok/container-retention-policy/blob/main/.github/dependabot.yaml) 👍 It will open a PR with the relevant release notes when there's a new action version available.

Let me know if this misses out on some other benefit of a v3 tag that I haven't considered!

**Comment by ubbeK** [comment]
Everybody does it differently regarding tags and mutable tags. I personally prefer mutable tags for major-tag and minor-tag (examples `v3`, `v3.1`) which gives the freedom for the end user to choose what kind of tag to use. As long as SemVer 2.0 is followed regarding the interface (input/output variable names and type/format), then I wouldn't effectively be targeting the main branch when using the major mutable tag. At the same time, I could target minor mutable tag to lock in on a specific state, but still get all patch fixes.

I am personally maintaining a few github actions and reusable github action workflows which are located in several private git repos, and I would like to share my workflow for PR merges which implements what I discussed above. I am not saying that you should implement it yourself, as I get that it is hard to test all scenarios for a small/medium sized opensource project.

```
on:
  pull_request: # on merge to main only, see if-statement: github.event.pull_request.merged == true
    branches:
    - main
    types:
    - closed

jobs:
  pr_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # due to paulhatch/semantic-version step below

    - name: Get next semver version
      id: get_version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        version_format: "${major}.${minor}.${patch}"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        search_commit_body: true

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ steps.get_version.outputs.version_tag }}" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${{ steps.get_version.outputs.version_tag }}" \
          --generate-notes

        git tag --force v${{ steps.get_version.outputs.major }}
        git push origin v${{ steps.get_version.outputs.major }} --force

        git tag --force v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
        git push origin v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }} --force

    - name: PR comment
      uses: actions/github-script@v7
      with:
        retries: 3
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Release [${{ steps.get_version.outputs.version_tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_version.outputs.version_tag }}) created on SHA ${{ github.sha }}.\n\n' +
                  'Tag [v${{ steps.get_version.outputs.major }}](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.get_version.outputs.major }}) created on SHA ${{ github.sha }}.\n\n' +
                  'Tag [v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}) created on SHA ${{ github.sha }}.'
          })
```

Keep up the good work, and I will definitely check out the dependabot example you supplied. Thanks!

**Comment by raszi** [comment]
I am having issues defining a rule that would remove every outdated images but the skipped ones: The previous config looked like this:

```yaml
image-names: metric
cut-off: One month ago UTC
keep-at-least: 1
account-type: personal
skip-tags: base, production
token: ${{ secrets.GITHUB_TOKEN }}
token-type: github-token
```

The new:
```yaml
account: user
token: ${{ secrets.GITHUB_TOKEN }}
image-names: metric
image-tags: * !base !production
cut-off: 4w
keep-n-most-recent: 1
```

But this does not work.

**Comment by sondrelg** [comment]
Please try `image-tags: !base, !production` or `image-tags: !base !production` @raszi 👍 The wildcard is implicit as long as no positive matchers (expressions without `!` prefixed) are specified.

**Comment by raszi** [comment]
That does not work either. 😔 Now it is complaining about the `with:` line.

**Comment by sondrelg** [comment]
See [this example](https://github.com/snok/container-retention-policy/blob/main/.github/workflows/live_test.yaml#L26:L38) which does the same thing. 

Is your workflow public?

**Comment by ubbeK** [comment]
> That example is not exactly the same, because that has an explicit wildcard. With the explicit wildcard, I get the error when I use `*`, as I pasted above. Without the explicit wildcard, I get the error on the `with:`. level. If I use an explicit wildcard that looks like the example you linked (like `t*`), it has no errors, but that is not the same behavior.
> 
> No, unfortunately, the workflow is not public.

I would guess that you need to make the yaml property it into a string not not get that `with` error, like

```
account: user
token: ${{ secrets.GITHUB_TOKEN }}
image-names: foo
image-tags: "!base !production"
cut-off: 4w
keep-n-most-recent: 1
```

**Comment by raszi** [comment]
I am unsure how the YAML file is handled by this project, but will that work the same way? Wouldn't it try to ignore images with tags `base !production`?

**Comment by sondrelg** [comment]
It should work the same way, but I'd suggest running the action with `dry-run: true` if you want to be sure

**Comment by raszi** [comment]
This is my current step definition:

```
  clean-old-images:
    name: Delete old unused images
    runs-on: ubuntu-latest

    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: foo
          image-tags: "!base !production"
          cut-off: 4w
          keep-n-most-recent: 1
```
