### ISSUE TITLE
allow skip-tags with wildcard

### ISSUE THREAD

**Issue by Emilgardis** [snok/container-retention-policy#9]
A feature I'm missing from this action is the ability to skip multiple tags by matching with a wildcard

This would be for example:

```
- uses: snok/container-retention-policy@v1
  with:
    image-names: dev, web, test
    cut-off: two hours ago UTC+2
    timestamp-to-use: updated_at
    account-type: org
    org-name: google
    keep-at-least: 1
    skip-tags: latest, latest-*
    token: ${{ secrets.PAT }}
```

This would allow me to not cleanup tags which match latest-*

It would be even better if there was regex support, but for that to work, I don't think the `,` separator would work well, thinking of `\d{0,2}` for example

Maybe if it was instead/also accepted

```
skip-tags: | 
  latest
  v.*
```
